In [28]:
import pandas as pd
import numpy as np

In [29]:
df=pd.read_csv("F:/ML_algo/datasets/customer.csv")
df.sample(4)

    age  gender   review education purchased
17   22  Female     Poor        UG       Yes
32   92    Male  Average        UG       Yes
8    65  Female  Average        UG        No
26   53  Female     Poor        PG        No

In [30]:
df.shape

(50, 5)

In [31]:
# df.info()

In [32]:
df = df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [80]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [81]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],
                                              df.iloc[:,-1])

In [82]:
X_train

     review education
44  Average        UG
31     Poor    School
48     Good        UG
29  Average        UG
27     Poor        PG
5   Average    School
9      Good        UG
42     Good        PG
3      Good        PG
40     Good    School
33     Good        PG
26     Poor        PG
34  Average    School
47     Good        PG
16     Poor        UG
25     Good    School
21  Average        PG
11     Good        UG
13  Average    School
41     Good        PG
17     Poor        UG
1      Poor        UG
8   Average        UG
36     Good        UG
19     Poor        PG
37  Average        PG
10     Good        UG
0   Average    School
7      Poor    School
43     Poor        PG
46     Poor        PG
39     Poor        PG
6      Good    School
15     Poor        UG
45     Poor        PG
28     Poor    School
18     Good    School

In [83]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [84]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [86]:
X_train = oe.transform(X_train)

In [87]:
X_train

array([[1., 1.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [76]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [77]:
X_train

array([[2., 2.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [2., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.]])

In [88]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
y_train

In [94]:
le=LabelEncoder()

In [95]:
le.fit(y_train)

LabelEncoder()

In [96]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [97]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [98]:
y_train

array([0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0])

In [99]:
y_test

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0])