In [1]:
import numpy as np 
import pandas as pd

In [2]:
date=pd.read_csv("F:/ML_algo/datasets/orders.csv")
time=pd.read_csv("F:/ML_algo/datasets/messages.csv")

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## working with dates

In [7]:
# converting to datetime datatype
date['date']= pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1 ectract year

In [10]:
date['date_year']=date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

### 2. extract months

In [13]:
date['date_month']=date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [19]:
date['date_month_name']=date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name
0,2019-12-10,5628,25,3,2019,December,1,December
1,2018-08-15,3646,14,157,2018,August,2,August
2,2018-10-23,1859,25,1,2018,October,1,October
3,2019-08-17,7292,25,1,2019,August,5,August
4,2019-01-06,4344,25,3,2019,January,6,January

In [21]:
date['date_day']=date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name
0,2019-12-10,5628,25,3,2019,December,10,December
1,2018-08-15,3646,14,157,2018,August,15,August
2,2018-10-23,1859,25,1,2018,October,23,October
3,2019-08-17,7292,25,1,2019,August,17,August
4,2019-01-06,4344,25,3,2019,January,6,January

In [23]:
date['date_dow']=date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_dow
0,2019-12-10,5628,25,3,2019,December,1,December,1
1,2018-08-15,3646,14,157,2018,August,2,August,2
2,2018-10-23,1859,25,1,2018,October,1,October,1
3,2019-08-17,7292,25,1,2019,August,5,August,5
4,2019-01-06,4344,25,3,2019,January,6,January,6

In [24]:
date['date_dow_name']=date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name
0,2019-12-10,5628,25,3,2019,December,1,December,1,Tuesday
1,2018-08-15,3646,14,157,2018,August,2,August,2,Wednesday
2,2018-10-23,1859,25,1,2018,October,1,October,1,Tuesday
3,2019-08-17,7292,25,1,2019,August,5,August,5,Saturday
4,2019-01-06,4344,25,3,2019,January,6,January,6,Sunday

In [25]:
# is weekend

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,1,December,1,Tuesday,0
1,2018-08-15,2018,August,2,August,2,Wednesday,0
2,2018-10-23,2018,October,1,October,1,Tuesday,0
3,2019-08-17,2019,August,5,August,5,Saturday,1
4,2019-01-06,2019,January,6,January,6,Sunday,1

### Extract week of the year

In [31]:

# date['date_week'] = date['date'].dt.week
# date.drop(columns=['product_id','city_id','orders']).head()

AttributeError: 'DatetimeProperties' object has no attribute 'week'

In [32]:

date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name,date_is_weekend,quarter
0,2019-12-10,2019,December,1,December,1,Tuesday,0,4
1,2018-08-15,2018,August,2,August,2,Wednesday,0,3
2,2018-10-23,2018,October,1,October,1,Tuesday,0,4
3,2019-08-17,2019,August,5,August,5,Saturday,1,3
4,2019-01-06,2019,January,6,January,6,Sunday,1,1

In [33]:
#  extract semester
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name,date_is_weekend,quarter,semester
0,2019-12-10,2019,December,1,December,1,Tuesday,0,4,2
1,2018-08-15,2018,August,2,August,2,Wednesday,0,3,2
2,2018-10-23,2018,October,1,October,1,Tuesday,0,4,2
3,2019-08-17,2019,August,5,August,5,Saturday,1,3,2
4,2019-01-06,2019,January,6,January,6,Sunday,1,1,1

## Extract Time elapsed between dates

In [35]:
import datetime
today= datetime.datetime.today()
today

datetime.datetime(2026, 1, 5, 16, 16, 47, 903635)

In [36]:
today - date['date']

0     2218 days 16:16:47.903635
1     2700 days 16:16:47.903635
2     2631 days 16:16:47.903635
3     2333 days 16:16:47.903635
4     2556 days 16:16:47.903635
                 ...
995   2646 days 16:16:47.903635
996   2587 days 16:16:47.903635
997   2435 days 16:16:47.903635
998   2500 days 16:16:47.903635
999   2274 days 16:16:47.903635
Name: date, Length: 1000, dtype: timedelta64[ns]

In [37]:
(today - date['date']).dt.days

0      2218
1      2700
2      2631
3      2333
4      2556
       ...
995    2646
996    2587
997    2435
998    2500
999    2274
Name: date, Length: 1000, dtype: int64

In [49]:
# Months passed
np.round((today - date['date']) / np.timedelta64(1, 'm'),0)

0      3194897.0
1      3888977.0
2      3789617.0
3      3360497.0
4      3681617.0
         ...
995    3811217.0
996    3726257.0
997    3507377.0
998    3600977.0
999    3275537.0
Name: date, Length: 1000, dtype: float64

### time

In [41]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [42]:
# Converting to datetime datatype
time['date']= pd.to_datetime(time['date'])

In [43]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [44]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

### Extract Time part

In [45]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [46]:
#  time difference
today - time['date']

0     4404 days 15:26:47.903635
1     4268 days 16:36:47.903635
2     4754 days 15:55:47.903635
3     4056 days 15:45:47.903635
4     4453 days 17:05:47.903635
                 ...
995   5043 days 15:26:47.903635
996   4364 days 17:02:47.903635
997   4829 days 16:39:47.903635
998   4945 days 16:42:47.903635
999   4217 days 16:51:47.903635
Name: date, Length: 1000, dtype: timedelta64[ns]

In [48]:
# in seconds

(today - time['date'])/np.timedelta64(1,'m')

0      6.342687e+06
1      6.146917e+06
2      6.846716e+06
3      5.841586e+06
4      6.413346e+06
           ...
995    7.262847e+06
996    6.285183e+06
997    6.954760e+06
998    7.121803e+06
999    6.073492e+06
Name: date, Length: 1000, dtype: float64

In [50]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      105711.446640
1      102448.613307
2      114111.929973
3       97359.763307
4      106889.096640
           ...
995    121047.446640
996    104753.046640
997    115912.663307
998    118696.713307
999    101224.863307
Name: date, Length: 1000, dtype: float64